/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f303xx.h"


int main(void)
{
	RCC_GPIOA_CLK_ENABLE();

	GPIO_InitTypeDef_t configure_struct = {0};
	configure_struct.Mode = GPIO_MODE_OUTPUT;
	configure_struct.Otype = GPIO_OTYPE_PP;
	configure_struct.Speed = GPIO_SPEED_HIGH;
	configure_struct.pinNumber = GPIO_PIN_5;

	GPIO_Init(GPIOA, &configure_struct);
	GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_Pin_Set);

    /* Loop forever */
	for(;;);
}
